Numpy array vs Python list

In [2]:
import numpy as np

In [4]:
#speed
#list
#Its without numpy
#Its speed is low
a=[i for i in range(10000000)]
b=[i for i in range(10000000, 20000000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

2.122389316558838


In [6]:
#numpy
#its speed is high by using numpy
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000, 20000000)
start=time.time()
c=a+b
print(time.time()-start)

0.07732558250427246


In [7]:
# memory
#without numpy
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)


89095160

In [9]:
#with numpy
a=np.arange(10000000, dtype=np.int8) #we use any int type such as 8,16,32... to reduce size
sys.getsizeof(a)

10000112

Advance Indexing

In [10]:
#normal indexing and slicing

a=np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
a[1:2]

array([[3, 4, 5]])

In [12]:
a[1,2]

5

In [17]:
a[1:3, 1:3]

array([[4, 5],
       [7, 8]])

In [25]:
#fancy Indexing

a[[0,2,3]] # that for row

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [26]:
a[:,[0,2]] # that for column

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9, 11]])

In [ ]:
# Boolean Indexing
