In [1]:
import numpy as np

In [2]:
a=np.random.randint(1,100,15)
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [3]:
np.sort(a)

array([ 3,  4,  9, 16, 16, 28, 29, 37, 59, 68, 68, 79, 84, 86, 88])

In [4]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[ 5, 11,  3, 85],
       [23, 87, 80, 82],
       [85, 50, 22, 90],
       [15, 86, 22,  2],
       [37,  9, 29, 56],
       [46, 53, 74, 79]])

In [5]:
np.sort(b) # we can do also by using rows and columns using axis

array([[ 3,  5, 11, 85],
       [23, 80, 82, 87],
       [22, 50, 85, 90],
       [ 2, 15, 22, 86],
       [ 9, 29, 37, 56],
       [46, 53, 74, 79]])

Np.append

In [6]:
np.append(a, 200)

array([  3,  79,  59,  28,   9,  84,  88,  29,   4,  68,  68,  86,  16,
        37,  16, 200])

In [7]:
b

array([[ 5, 11,  3, 85],
       [23, 87, 80, 82],
       [85, 50, 22, 90],
       [15, 86, 22,  2],
       [37,  9, 29, 56],
       [46, 53, 74, 79]])

In [8]:
np.append(b, np.ones((b.shape[0],1)), axis=1)

array([[ 5., 11.,  3., 85.,  1.],
       [23., 87., 80., 82.,  1.],
       [85., 50., 22., 90.,  1.],
       [15., 86., 22.,  2.,  1.],
       [37.,  9., 29., 56.,  1.],
       [46., 53., 74., 79.,  1.]])

Np.concatenate

In [9]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [10]:
np.concatenate((c,d), axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [11]:
np.concatenate((c,d), axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

Np.Unique

In [12]:
e=np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [13]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

Np.expand_dims

In [14]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [15]:
a.shape

(15,)

In [16]:
np.expand_dims(a, axis=0)

array([[ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16]])

In [17]:
np.expand_dims(a, axis=0).shape

(1, 15)

In [18]:
np.expand_dims(a, axis=1)

array([[ 3],
       [79],
       [59],
       [28],
       [ 9],
       [84],
       [88],
       [29],
       [ 4],
       [68],
       [68],
       [86],
       [16],
       [37],
       [16]])

In [19]:
np.expand_dims(a, axis=1).shape

(15, 1)

Np.where

In [20]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [21]:
np.where(a>50)

(array([ 1,  2,  5,  6,  9, 10, 11]),)

In [22]:
np.where(a>50, 0, a)

array([ 3,  0,  0, 28,  9,  0,  0, 29,  4,  0,  0,  0, 16, 37, 16])

In [23]:
np.where(a%2==0, 0,a)

array([ 3, 79, 59,  0,  9,  0,  0, 29,  0,  0,  0,  0,  0, 37,  0])

np.argmax

In [24]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [25]:
np.argmax(a)


6

In [26]:
b

array([[ 5, 11,  3, 85],
       [23, 87, 80, 82],
       [85, 50, 22, 90],
       [15, 86, 22,  2],
       [37,  9, 29, 56],
       [46, 53, 74, 79]])

In [27]:
np.argmax(b, axis=0)

array([2, 1, 1, 2])

np.argmin

In [28]:
np.argmin(a)

0

Np.cumsum

In [29]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [30]:
np.cumsum(a)

array([  3,  82, 141, 169, 178, 262, 350, 379, 383, 451, 519, 605, 621,
       658, 674])

In [31]:
np.cumsum(b)

array([   5,   16,   19,  104,  127,  214,  294,  376,  461,  511,  533,
        623,  638,  724,  746,  748,  785,  794,  823,  879,  925,  978,
       1052, 1131])

In [32]:
np.cumsum(b, axis=0)

array([[  5,  11,   3,  85],
       [ 28,  98,  83, 167],
       [113, 148, 105, 257],
       [128, 234, 127, 259],
       [165, 243, 156, 315],
       [211, 296, 230, 394]])

np.cumprod

In [33]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [34]:
np.cumprod(a)

array([                   3,                  237,                13983,
                     391524,              3523716,            295992144,
                26047308672,         755371951488,        3021487805952,
            205461170804736,    13971359614722048,  1201536926866096128,
         777846756147986432, -8113158169943605248,  -683322203130822656])

np.percentile

In [35]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [36]:
np.percentile(a,100)

88.0

In [37]:
np.percentile(a, 0)

3.0

In [38]:
np.percentile(a, 50)

37.0

In [39]:
np.median(a)

37.0

Np.histogram

In [40]:
np.histogram(a, bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([3, 2, 2, 1, 0, 1, 2, 1, 3, 0]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

np.corrcoef

In [42]:
salary=np.array([20000,40000,25000,35000,60000])
experience=np.array([1,3,2,4,2])
np.corrcoef(salary, experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

np.isin

In [43]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [44]:
items=[10,20,30,40,50,60,70,80,90,100]

np.isin(a, items)

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

np.flip

In [45]:
a

array([ 3, 79, 59, 28,  9, 84, 88, 29,  4, 68, 68, 86, 16, 37, 16])

In [46]:
np.flip(a)

array([16, 37, 16, 86, 68, 68,  4, 29, 88, 84,  9, 28, 59, 79,  3])

In [47]:
b

array([[ 5, 11,  3, 85],
       [23, 87, 80, 82],
       [85, 50, 22, 90],
       [15, 86, 22,  2],
       [37,  9, 29, 56],
       [46, 53, 74, 79]])

In [48]:
np.flip(b)

array([[79, 74, 53, 46],
       [56, 29,  9, 37],
       [ 2, 22, 86, 15],
       [90, 22, 50, 85],
       [82, 80, 87, 23],
       [85,  3, 11,  5]])

In [49]:
np.flip(b, axis=1)

array([[85,  3, 11,  5],
       [82, 80, 87, 23],
       [90, 22, 50, 85],
       [ 2, 22, 86, 15],
       [56, 29,  9, 37],
       [79, 74, 53, 46]])

np.put

In [54]:
a

array([110, 530,  59, 343,   9,  84,  88,  29,   4,  68,  68,  86,  16,
        37,  16])

In [51]:
np.put(a, [0,1], [110,530])

In [53]:
np.put(a, [3],[343])

np.delete

In [55]:
a

array([110, 530,  59, 343,   9,  84,  88,  29,   4,  68,  68,  86,  16,
        37,  16])

In [56]:
np.delete(a, 0)

array([530,  59, 343,   9,  84,  88,  29,   4,  68,  68,  86,  16,  37,
        16])

In [58]:
np.delete(a, [2,4])

array([110, 530, 343,  84,  88,  29,   4,  68,  68,  86,  16,  37,  16])

set funcitons:
np.union1d
np.intersect1d
np.setdiff1d
np.setxor1d
np.setxor1d
np.in1d

In [62]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,67,7])
np.union1d(m,n)

array([ 1,  2,  3,  4,  5,  7, 67])

In [63]:
np.intersect1d(m,n)

array([3, 4, 5])

In [64]:
np.setdiff1d(m,n)

array([1, 2])

In [65]:
np.setxor1d(m, n)

array([ 1,  2,  7, 67])

In [66]:
np.in1d(m,1)

array([ True, False, False, False, False])

np.clip

In [67]:
a

array([110, 530,  59, 343,   9,  84,  88,  29,   4,  68,  68,  86,  16,
        37,  16])

In [68]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 59, 75, 25, 75, 75, 29, 25, 68, 68, 75, 25, 37, 25])